export const SOCKET_EVENTS = {
    CONNECT: 'connect',
    DISCONNECT: 'disconnect',
    CONNECT_ERROR: 'connect_error',
    ERROR: 'error',
    MESSAGE_RECEIVED: 'message received',
    MESSAGE_SEND: 'message send',
    JOIN_ROOM: 'join room',
    SETUP: 'setup',
    CONVERSATION_ASSIGNED_USER: 'conversation assigned user',
    CLOSED_CONVERSATION_USER: 'close conversation received',
    FEEDBACK_REQUEST: 'feedback-request',
    FEEDBACK_RESPONSE: 'feedback-response',
    FEEDBACK_RECEIVED: 'feedback-received',
};